name = "mail2telegram"
main = "index.js"
compatibility_date = "2024-06-03"
kv_namespaces = [
  { binding = "DB", id = "" }
]

[vars]
DOMAIN = "mail2telegram.YOUR_NAME.workers.dev"
TELEGRAM_ID = "YOUR_TELEGRAM_ID"
TELEGRAM_TOKEN = "YOUR_TELEGRAM_TOKEM"
FORWARD_LIST = "YOUR_BACKUP_EMAIL"

OPENAI_API_KEY = "sk-"
# OPENAI_COMPLETIONS_API = "https://openrouter.ai/api/v1/chat/completions"
# OPENAI_CHAT_MODEL = "openai/gpt-4o-mini"
# SUMMARY_TARGET_LANG = "chinese"

# WHITE_LIST = "Suggested settings in the Telegram mini apps"
# BLOCK_LIST = "Suggested settings in the Telegram mini apps"
# MAIL_TTL = "3600"


GUARDIAN_MODE = "false"
#MAX_EMAIL_SIZE = "524288"
MAX_EMAIL_SIZE_POLICY = "truncate"
DEBUG = "false"

