name = "mail2telegram"
main = "index.ts"
compatibility_date = "2023-10-13"

kv_namespaces = [
  { binding = "DB", id = "" }
]

[vars]
DOMAIN = "mail2telegram.yourname.workers.dev"
TELEGRAM_ID = ""
TELEGRAM_TOKEN = ":"
FORWARD_LIST = "yourname@outlook.com"
